/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function BaseDetails(props) {
  const { nodes, materials } = useGLTF("./BaseDetails.glb");
  return (
    <group {...props} dispose={null}>
    <group position={[0, 0.83512026, -0.00001526]} scale={1.05212128}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002_1.geometry}
        material={materials.base}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002_2.geometry}
        material={materials.faixa}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002_3.geometry}
        material={materials.bordatop}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002_4.geometry}
        material={materials.basechao}
      />
    </group>
  </group>
  );
}

useGLTF.preload("./BaseDetails.glb");
