/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function BonecoDeNeve(props) {
  const { nodes, materials } = useGLTF("./BonecoDeNeve.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-1.05182481, 4.82197285, 18.14031601]}
        rotation={[-Math.PI, 0.90336247, -Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve002.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve002_1.geometry}
          material={materials.botao}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve002_2.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve002_3.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve002_4.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve002_5.geometry}
          material={materials.cachecol}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve002_6.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve002_7.geometry}
          material={materials.cachcol2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve002_8.geometry}
          material={materials.cachecol3}
        />
      </group>
      <group
        position={[-0.27313751, 6.90242147, 18.2684288]}
        rotation={[-1.44395053, 0.88097037, -1.74579479]}
        scale={[0.11878259, 0.11878259, 0.1187826]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1.geometry}
          material={materials.branco}
        />
      </group>
      <group
        position={[-3.45214272, 2.41391182, 23.41118431]}
        rotation={[-2.01733804, 0.75375045, -0.93293805]}
        scale={[0.04476174, 0.04476174, 0.04476173]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_2.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_3.geometry}
          material={materials.branco}
        />
      </group>
      <group
        position={[-5.19514942, 3.21280766, 20.38251495]}
        rotation={[-2.38095777, 0, 0]}
        scale={0.06563093}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_4.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_5.geometry}
          material={materials.branco}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./BonecoDeNeve.glb");
