/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, MeshReflectorMaterial,useTexture  } from "@react-three/drei";
import { useBox } from "@react-three/cannon";



export function Floor(props) {

  const asphaltTexture = useTexture("./Textures/asphalt.jpg")
  const [ref] = useBox(() => ({
    type: "Static",
    position: [0, 0.1, 0],
    rotation: [0, 0, 0],
    args: [1000, 0.1, 1000],
    
  }));

  return (
<group {...props} dispose={null}>
<mesh  position-y={0.2}  rotation-x={ -Math.PI * 0.5} scale={300}
      castShadow
      receiveShadow> 
      

<planeGeometry/>

<MeshReflectorMaterial mirror={0.3} resolution={1024} map={asphaltTexture} mixBlur={10}/>

</mesh>
    </group>
  );
}

useGLTF.preload("./Floor.glb");
