/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF,useTexture } from "@react-three/drei";
import { MeshStandardMaterial } from "three";
import * as THREE from 'three'

export function Foliage(props) {




  const { nodes, materials } = useGLTF("./Foliage.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-15.63792896, 1.83214557, -20.92712021]}
        scale={[0.54148549, 3.94643044, 0.54148549]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035_1.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <group
        position={[-15.09849358, 13.29815292, -17.94096565]}
        rotation={[-0.6606122, -0.90436476, -0.54833395]}
        scale={[0.85430932, 0.93192005, 2.03630376]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_1.geometry}
          material={materials["Material.014"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.caule03.geometry}
        material={materials["Material.019"]}
        position={[-15.94728184, 6.76070309, 19.53725815]}
        scale={[0.19534613, 1.36440361, 0.19534613]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.caule02.geometry}
        material={materials["Material.019"]}
        position={[-15.37338066, 6.20502567, -19.66226387]}
        rotation={[-Math.PI, 1.5e-7, -Math.PI]}
        scale={[0.17351705, 1.21193743, 0.17351705]}
      />
      <group
        position={[-16.37757683, 13.90187168, 17.46297646]}
        rotation={[-2.10775136, 1.11359078, 2.15656199]}
        scale={[0.77725792, 0.8478688, 1.85264671]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_1.geometry}
          material={materials["Material.014"]}
        />
      </group>
      <group
        position={[15.07503605, 12.26251698, 18.21930695]}
        rotation={[-2.23974962, 1.06610854, 2.30535007]}
        scale={[0.85430932, 0.93192005, 2.03630376]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials["Material.014"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.caule03001.geometry}
        material={materials["Material.019"]}
        position={[15.90333843, 7.585495, -19.60214424]}
        rotation={[Math.PI, -1.5e-7, Math.PI]}
        scale={[0.19534613, 1.36440361, 0.19534613]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.caule02001.geometry}
        material={materials["Material.019"]}
        position={[-1.29915321, -0.68113768, 1.43130779]}
        scale={[0.17351705, 1.21193743, 0.17351705]}
      />
      <group
        position={[-1.5005827, -0.49416947, -1.1823988]}
        rotation={[-1.03384153, -1.11359076, -0.98503085]}
        scale={[0.77725792, 0.8478688, 1.85264647]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={materials["Material.014"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Foliage.glb");
