/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PilarArvore(props) {
  const { nodes, materials } = useGLTF("./PilarArvore.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials.ferro}
        position={[0, 0, 0]}
        scale={[0.50564665, 1, 0.50564665]}
      />
    </group>
  );
}

useGLTF.preload("./PilarArvore.glb");
