/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Rocks(props) {
  const { nodes, materials } = useGLTF("./Rocks.glb");
  return (
    <group {...props} dispose={null}>
   <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        material={materials.snowrock}
        position={[-151.656, 16.627, 33.541]}
        rotation={[0, 0, -0.599]}
        scale={[3.598, 2.215, 3.598]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere002.geometry}
        material={materials.snowrock}
        position={[-123.719, 3.296, 77.715]}
        rotation={[0.006, 0.356, -2.31]}
        scale={[2.991, 1.841, 2.991]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere005.geometry}
        material={materials.snowrock}
        position={[-101.068, 1.811, 54.067]}
        rotation={[-1.276, 0.839, 0.84]}
        scale={[1.029, 0.633, 1.029]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere006.geometry}
        material={materials.snowrock}
        position={[-114.743, 91.011, 182.905]}
        rotation={[-1.161, 0.572, 0.798]}
        scale={[2.4, 1.478, 2.4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere007.geometry}
        material={materials.snowrock}
        position={[-226.119, 63.489, 63.986]}
        rotation={[0.087, 0.542, -0.68]}
        scale={[6.292, 5.075, 2.51]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere008.geometry}
        material={materials.snowrock}
        position={[-177.035, 99.497, 151.709]}
        rotation={[-2.954, -0.112, 2.978]}
        scale={[6.31, 3.884, 6.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere011.geometry}
        material={materials.snowrock}
        position={[194.963, 15.215, 18.696]}
        rotation={[3.107, 0.912, 0.042]}
        scale={[3.474, 2.138, 3.474]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere012.geometry}
        material={materials.snowrock}
        position={[163.973, 14.519, 26.784]}
        rotation={[-2.938, -0.229, -0.566]}
        scale={[2.241, 1.379, 2.241]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere015.geometry}
        material={materials.snowrock}
        position={[200.429, 17.846, -59.193]}
        rotation={[0.105, -1.364, -3.025]}
        scale={[3.474, 2.138, 3.474]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere017.geometry}
        material={materials.snowrock}
        position={[-117.95, 13.443, -137.573]}
        rotation={[-2.892, 0.723, 2.789]}
        scale={[1.319, 0.812, 1.319]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere019.geometry}
        material={materials.snowrock}
        position={[-78.537, 13.32, -143.257]}
        rotation={[0.111, 1.376, 3.047]}
        scale={[3.474, 2.138, 3.474]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere021.geometry}
        material={materials.snowrock}
        position={[31.183, 22.689, -228.887]}
        rotation={[-0.472, -1.151, -0.621]}
        scale={[4.032, 2.482, 4.032]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere023.geometry}
        material={materials.snowrock}
        position={[-16.308, 15.95, -190.417]}
        rotation={[3.106, -0.924, -0.014]}
        scale={[3.474, 2.138, 3.474]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere024.geometry}
        material={materials.snowrock}
        position={[21.688, 20.04, -181.931]}
        rotation={[-0.397, -1.037, 2.183]}
        scale={[2.241, 1.379, 2.241]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere025.geometry}
        material={materials.snowrock}
        position={[91.08, 10.872, -160.967]}
        rotation={[-0.472, -1.151, -0.621]}
        scale={[1.68, 1.034, 1.68]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere026.geometry}
        material={materials.snowrock}
        position={[-128.959, 8.064, -118.082]}
        rotation={[3.106, -0.924, -0.014]}
        scale={[1.447, 0.891, 1.447]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere028.geometry}
        material={materials.snowrock}
        position={[113.7, 12.392, -125.896]}
        rotation={[-0.192, 0.24, -0.139]}
        scale={[1.68, 1.034, 1.68]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere029.geometry}
        material={materials.snowrock}
        position={[126.932, 9.584, -104.14]}
        rotation={[0.03, -0.781, -3.106]}
        scale={[1.447, 0.891, 1.447]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere030.geometry}
        material={materials.snowrock}
        position={[132.557, 11.288, -119.353]}
        rotation={[-0.212, 0.357, 2.604]}
        scale={[0.934, 0.575, 0.934]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere032.geometry}
        material={materials.snowrock}
        position={[-92.647, 10.03, -112.633]}
        rotation={[0.03, -0.781, -3.106]}
        scale={[1.447, 0.891, 1.447]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere034.geometry}
        material={materials.snowrock}
        position={[0.835, 17.755, 128.904]}
        rotation={[-0.696, -0.165, -0.095]}
        scale={[3.622, 2.23, 3.622]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere035.geometry}
        material={materials.snowrock}
        position={[9.987, 40.659, 178.331]}
        rotation={[-0.203, -1.149, -2.785]}
        scale={[3.121, 1.921, 3.121]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere037.geometry}
        material={materials.snowrock}
        position={[89.094, 6.445, 131.285]}
        rotation={[-1.351, 1.157, 0.63]}
        scale={[0.703, 0.433, 0.703]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere038.geometry}
        material={materials.snowrock}
        position={[144.935, 27.399, 117.041]}
        rotation={[-0.536, 0.265, -3.011]}
        scale={[3.121, 1.921, 3.121]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere039.geometry}
        material={materials.snowrock}
        position={[122.362, 14.753, 93.224]}
        rotation={[-1.628, 1.216, -2.659]}
        scale={[2.013, 1.239, 2.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere040.geometry}
        material={materials.snowrock}
        position={[50.066, 30.364, 165.413]}
        rotation={[-1.351, 1.157, 0.63]}
        scale={[3.622, 2.23, 3.622]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere042.geometry}
        material={materials.snowrock}
        position={[74.008, 9.03, 139.646]}
        rotation={[-2.263, 0.094, 0.893]}
        scale={[1.065, 0.656, 1.065]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere044.geometry}
        material={materials.snowrock}
        position={[108.937, 6.392, 84.849]}
        rotation={[-0.405, 0.082, -0.667]}
        scale={[0.703, 0.433, 0.703]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere046.geometry}
        material={materials.snowrock}
        position={[98.097, 2.986, 72.708]}
        rotation={[-1.602, 0.696, -0.515]}
        scale={[1.065, 0.656, 1.065]}
      />
    </group>
  );
}

useGLTF.preload("./Rocks.glb");
