/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function SnowRoofTop(props) {
  const { nodes, materials } = useGLTF("./SnowRoofTop.glb");
  return (
    <group {...props} dispose={null}>

        <mesh
        castShadow
        receiveShadow
        geometry={nodes.DIGITAL_LED02001.geometry}
        material={materials["Material.035"]}
        position={[-0.129, 17.069, -17.238]}
        rotation={[-Math.PI, 0, 0]}
        scale={[10.486, 0.324, 17.332]}
      />
    </group>
  );
}

useGLTF.preload("./SnowRoofTop.glb");
