/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ThreeJsJourney(props) {
  const { nodes, materials } = useGLTF("./threejsjourney.glb");
  return (
    <group {...props} dispose={null}>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Text001.geometry}
      material={materials.letras01}
      position={[-9.57071495, 41.55897903, 149.92417908]}
      rotation={[2.01062087, -0.05579497, -3.04593968]}
      scale={[1.29305041, 1.29305053, 1.29305065]}
    />
  </group>
  );
}

useGLTF.preload("./threejsjourney.glb");
